--- This contains a list of all files that will be loaded and the order they are loaded in;
-- to stop a file from loading add "--" in front of it, remove the "--" to have the file be loaded;
-- config files should be loaded after all modules are loaded;
-- core files should be required by modules and not be present in this list;
-- @config File-Loader
return {
    --'example.file_not_loaded',
    'modules.factorio-control', -- base factorio free play scenario
    'expcore.player_data',



    'config.oarc',
    'config.advanced_start',
    'config.afk_kick',
    'config.bonus',
    'config.chat_reply',
    'config.compilatron',
    'config.death_logger',
    'config.deconlog',
    'config.discord_alerts',
    'config.expcore.command_auth_admin',
    'config.expcore.command_auth_roles',
    'config.expcore.command_color_parse',
    'config.expcore.command_general_parse',
    'config.expcore.command_role_parse',
    'config.expcore.command_runtime_disable',
    'config.expcore.permission_groups',
    'config.expcore.roles',
    -- 'config.gamemodes.biterspawn',
    'config.graftorio',
    'config.gui.autofill',
    'config.gui.player_list_actions',
    'config.gui.rockets',
    'config.gui.science',
    'config.gui.tasks',
    'config.gui.warps',
    'config.inventory_clear',
    'config.join_messages',
    'config.nukeprotect',
    'config.personal_logistic',
    'config.pollution_grading',
    'config.popup_messages',
    'config.preset_player_colours',
    'config.preset_player_quickbar',
    'config.protection',
    'config.repair',
    'config.research',
    'config.scorched_earth',
    -- 'config.spawn_area',
    'config.station_auto_name',
    'config.statistics',
    'config.vlayer',
    'config.warnings',
    'config.oarc',
    'modules.addons.advanced-start',
    'modules.addons.afk-kick',
    'modules.addons.awflogging',
    'modules.addons.chat-popups',
    'modules.addons.chat-reply',
    'modules.addons.compilatron',
    'modules.addons.damage-popups',
    'modules.addons.death-logger',
    'modules.addons.deconlog',
    'modules.addons.discord-alerts',
    'modules.addons.fagc',
    'modules.addons.inserter',
    'modules.addons.inventory-clear',
    'modules.addons.miner',
    'modules.addons.nukeprotect',
    'modules.addons.pollution-grading',
    'modules.addons.protection-jail',
    'modules.addons.report-jail',
    'modules.addons.scorched-earth',
    -- 'modules.addons.spawn-area',
    'modules.addons.station-auto-name',
    'modules.addons.tree-decon',
    'modules.addons.tools',
    'modules.addons.spawns',
    'modules.control.vlayer',
    'modules.commands.admin-chat',
    'modules.commands.admin-markers',
    'modules.commands.bot-queue',
    'modules.commands.cheat-mode',
    'modules.commands.clear-inventory',
    'modules.commands.connect',
    'modules.commands.debug',
    'modules.commands.enemy',
    'modules.commands.find',
    'modules.commands.friendly-fire',
    'modules.commands.help',
    'modules.commands.home',
    'modules.commands.interface',
    'modules.commands.jail',
    'modules.commands.kill',
    'modules.commands.last-location',
    'modules.commands.lawnmower',
    'modules.commands.linkme',
    'modules.commands.me',
    'modules.commands.pollution',
    'modules.commands.protection',
    'modules.commands.rainbow',
    'modules.commands.ratio',
    'modules.commands.repair',
    'modules.commands.reports',
    'modules.commands.research',
    'modules.commands.roles',
    'modules.commands.search',
    'modules.commands.spawn',
    'modules.commands.spectate',
    'modules.commands.speed',
    'modules.commands.teleport',
    'modules.commands.train',
    'modules.commands.vlayer',
    'modules.commands.warnings',
    'modules.commands.waterfill',
    'modules.data.alt-view',
    'modules.data.bonus',
    'modules.data.greetings',
    'modules.data.language',
    'modules.data.personal-logistic',
    'modules.data.player-colours',
    'modules.data.quickbar',
    'modules.data.statistics',
    'modules.data.tag',
    -- 'modules.gamemodes.biterspawn',
    'modules.gui.autofill',
    'modules.gui.debug.event_view',
    'modules.gui.debug.expcore_datastore_view',
    'modules.gui.debug.expcore_gui_view',
    'modules.gui.debug.global_view',
    'modules.gui.debug.main_view',
    'modules.gui.debug.model',
    'modules.gui.debug.package_view',
    'modules.gui.debug.redmew_global_view',
    'modules.gui.debug._g_view',
    'modules.gui.logo',
    'modules.gui.player-list',
    'modules.gui.readme',
    'modules.gui.research',
    'modules.gui.rocket-info',
    'modules.gui.science-info',
    'modules.gui.server-ups',
    'modules.gui.task-list',
    'modules.gui.vlayer',
    'modules.gui.warp-list',
  
--     --- Game Commands
--     'modules.commands.admin-chat',
--     'modules.commands.admin-markers',
--     'modules.commands.debug',
--     'modules.commands.me',
--     'modules.commands.kill',
--     'modules.commands.teleport',
--     'modules.commands.cheat-mode',
--     'modules.commands.ratio',
--     'modules.commands.interface',
--     'modules.commands.help',
--     'modules.commands.roles',
--     'modules.commands.rainbow',
--     'modules.commands.clear-inventory',
--     'modules.commands.jail',
--     'modules.commands.repair',
--     'modules.commands.reports',
--     'modules.commands.spawn',
--     'modules.commands.warnings',
--     'modules.commands.find',
--     'modules.commands.home',
--     'modules.commands.connect',
--     'modules.commands.linkme',
--     'modules.commands.last-location',
--     'modules.commands.protection',
--     'modules.commands.spectate',
--     'modules.commands.search',
--     'modules.commands.bot-queue',
--     'modules.commands.speed',
--     'modules.commands.pollution',
--     'modules.commands.train',
--     'modules.commands.friendly-fire',
--     'modules.commands.lawnmower',
--     'modules.commands.research',
--     'modules.commands.vlayer',
--     'modules.commands.enemy',
--     'modules.commands.waterfill',

--     --- Addons
--     'modules.addons.chat-popups',
--     'modules.addons.damage-popups',
--     'modules.addons.death-logger',
--     'modules.addons.advanced-start',
--     'modules.addons.spawn-area',
--     -- 'modules.addons.compilatron',
--     -- 'modules.addons.scorched-earth',
--     'modules.addons.pollution-grading',
--     'modules.addons.station-auto-name',
--     'modules.addons.discord-alerts',
--     'modules.addons.chat-reply',
--     'modules.addons.tree-decon', -- does decon control for everything
--     'modules.addons.awflogging', -- logging for JammyBot (AwF)
--     'modules.addons.afk-kick',
--     'modules.addons.report-jail',
--     'modules.addons.protection-jail',
-- 		'modules.addons.deconlog',
-- 		'modules.addons.nukeprotect',
-- 		'modules.addons.inserter',
--     'modules.addons.miner',

--     -- Control
--     'modules.control.vlayer',

--     --- Data
--     'modules.data.statistics',
--     'modules.data.player-colours',
--     'modules.data.greetings',
--     'modules.data.quickbar',
--     'modules.data.alt-view',
--     'modules.data.tag',
--     -- 'modules.data.bonus',
--     'modules.data.personal-logistic',
--     'modules.data.language',

--     --- GUI
--     'modules.gui.readme',
--     'modules.gui.rocket-info',
--     'modules.gui.science-info',
--     'modules.gui.autofill',
--     -- 'modules.gui.warp-list',
--     'modules.gui.task-list',
--     'modules.gui.player-list',
--     'modules.gui.server-ups',
--     'modules.gui.vlayer',
--     'modules.gui.research',

-- 		'modules.graftorio.require', -- graftorio

--     --- Config Files
--     'config.expcore.command_auth_admin', -- commands tagged with admin_only are blocked for non admins
--     'config.expcore.command_auth_roles', -- commands must be allowed via the role config
--     'config.expcore.command_runtime_disable', -- allows commands to be enabled and disabled during runtime
--     'config.expcore.permission_groups', -- loads some predefined permission groups
--     'config.expcore.roles', -- loads some predefined roles
}
